spring:
  application:
    name: TSM Atelier
    security:
      jwt:
        configuration:
          access-token-expiration-ms: 900000
          refresh-token-expiration-ms: 604800000
          issuer: https://tsm-atelier.local.tm
        key:
          public: classpath:public_key.pem
          private: classpath:private_key.pem
  datasource:
    url: jdbc:postgresql://localhost:5432/tsm_atelier_local_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

