application:
  jwt:
    configuration:
      role-claim-name: role
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:}:${DATABASE_PORT:}/${DATABASE_NAME:}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
security:
  allowed-paths:
    get:
      - /error
      - /api/v1/test/**
    post:
      - /api/v1/auth/**
      - /error