name: Build
on:
  push:
    paths:
      - 'src/**/*.kt'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
    branches:
      - main
  pull_request:
    paths:
      - 'src/**/*.kt'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Build
        run: ./gradlew build --no-daemon