name: Upgrade Gradle wrapper
on:
  schedule:
    - cron: "0 3 * * MON"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup JDK
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Get current gradle version
        run: |
          ./gradlew --version
          VERSION=$(./gradlew --version | grep "Gradle" | awk '{print $2}')
          echo "CURRENT_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Upgrade Gradle wrapper
        run: ./gradlew wrapper --gradle-version latest
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get latest gradle version
        run: |
          ./gradlew --version
          VERSION=$(./gradlew --version | grep "Gradle" | awk '{print $2}')
          echo "LATEST_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Check if a PR for the latest Gradle version is already open
        id: list_prs
        uses: actions/github-script@v7
        with:
          script: |
            const pullRequests = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
            });
            const matchingPR = pullRequests.data.find(pr =>
              pr.title.includes(`Upgrade Gradle wrapper from`) &&
              pr.title.includes(`to ${{ env.LATEST_VERSION }}`)
            );
            core.setOutput("pr_exists", matchingPR ? "true" : "false");
      - name: Create pull request
        if: steps.list_prs.outputs.pr_exists == 'false'
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: build/upgrade-gradle-wrapper-${{ steps.date.outputs.date }}
          commit-message: 'build: upgrade Gradle wrapper to ${{ env.LATEST_VERSION }}'
          title: Upgrade Gradle wrapper from ${{ env.CURRENT_VERSION }} to ${{ env.LATEST_VERSION }}
          body: |
            Auto-generated by [upgrade-gradle-wrapper.yml][1] 
            [1]: https://github.com/thierrysm/tsm-atelier/actions/workflows/upgrade-gradle-wrapper.yml
