name: Upgrade Gradle wrapper
on:
  schedule:
    - cron: "0 3 * * MON"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Setup JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Upgrade Gradle wrapper
        run: ./gradlew wrapper --gradle-version latest
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: build/upgrade-gradle-wrapper-${{ steps.date.outputs.date }}
          commit-message: 'build: upgrade Gradle wrapper'
          title: Upgrade Gradle wrapper
          body: |
            - Upgrade Gradle wrapper
            Auto-generated by [upgrade-gradle-wrapper.yml][1] 
            [1]: https://github.com/thierrysm/tsm-atelier/actions/workflows/upgrade-gradle-wrapper.yml
